/**
 * Wörterbuch: Schale, Navigation, Charakterliste und Wochenübersicht.
 *
 * Englisch definiert die Schlüssel, Deutsch muss sie vollständig bedienen –
 * das erzwingt der Typ unten. Platzhalter stehen in geschweiften Klammern.
 */

export const en = {
  "app.title": "WoW Dashboard",
  "app.description": "World of Warcraft account overview",
  "app.brand": "WOW DASHBOARD",
  "app.tagline": "Roster / local",

  "header.apiConnected": "Dev API connected",
  "header.firstFetch": "First fetch running…",
  "header.updated": "Updated {seconds} sec ago",
  "header.pollEvery": "Fetch every {seconds} sec.",
  "header.charactersFound": "{count} characters found",
  "header.collections": "Collections",
  "header.settings": "Settings",
  "header.signOut": "Sign out",

  "theme.label": "Colour scheme",
  "theme.light": "Light",
  "theme.dark": "Dark",

  "language.label": "Language",

  "dashboard.myCharacters": "My characters",
  "dashboard.myCharactersHint":
    "All characters on the account · the dev API keeps pulling automatically",
  "dashboard.loading": "Loading…",

  // ─── Anmeldung ───────────────────────────────────────────────────────────
  "time.now": "now",
  "time.daysHours": "{days}d {hours}h",
  "time.hoursMinutes": "{hours}h {minutes}m",
  "time.minutes": "{minutes}m",

  // ─── Spielmodi ───────────────────────────────────────────────────────────
  "mode.retail": "Retail",
  "mode.retail.note": "The War Within · level 80",
  "mode.classic": "Classic",
  "mode.classic.note": "Anniversary · level 60",
  "mode.classicEra": "Classic Era",
  "mode.classicEra.note": "Hardcore · level 60",

  // ─── Charakter-Tabs ──────────────────────────────────────────────────────
  "tab.equipment": "Gear",
  "tab.equipment.note": "Equipped items and loot candidates",
  "tab.professions": "Professions",
  "tab.professions.note": "Skill levels and recipes",
  "tab.progress": "Progress",
  "tab.progress.note": "Raids, dungeons, Mythic+",
  "tab.collections": "Collections",
  "tab.collections.note": "Titles and toys",
  "tab.achievements": "Achievements",
  "tab.achievements.note": "Achievements by category",
  "tab.reputation": "Reputation",
  "tab.reputation.note": "Standing with factions",
  "tab.pvp": "PvP",
  "tab.pvp.note": "Ratings and battlegrounds",
  "tab.guild": "Guild",
  "tab.guild.note": "Members, achievements, events",
  "tab.economy": "Economy",
  "tab.economy.note": "Crafting cost against sale price",
  "tab.logs": "Logs",
  "tab.logs.note": "Warcraft Logs",
  "tab.history": "History",
  "tab.history.note": "Development over time",

  // ─── Charakterzeile ──────────────────────────────────────────────────────
  "card.itemLevel": "ILVL",
  "card.level": "Level",
  "card.averageItemLevel": "Ø ilvl",
  "card.faction": "Faction",
  "card.alliance": "Alliance",
  "card.horde": "Horde",
  "card.favoriteAdd": "Add to favourites",
  "card.favoriteRemove": "Remove from favourites",
  "card.gear": "Gear",
  "card.loading": "Loading",

  "weekly.link": "Weekly overview",

  // ─── Wochenübersicht ─────────────────────────────────────────────────────
  "weekly.account": "{mode} · account",
  "weekly.heading": "Weekly overview",
  "weekly.intro":
    "What has already been cleared in the current lockout period, derived from the timestamp of the last boss kill. The profile API only updates on logout — anyone still inside the instance is missing here.",
  "weekly.back": "← Back to the roster",
  "weekly.weeklyResetIn": "Weekly reset in",
  "weekly.dailyResetIn": "Daily reset in",
  "weekly.dailyResetInUncertain": "Daily reset in (time unverified)",
  "weekly.openInstances": "Open instances",
  "weekly.region": "Region {region}",
  "weekly.regionAssumed":
    "Reset times are not documented for this region; the European values are shown.",
  "weekly.regionKnown":
    "Reset times from a maintained table, calculated in UTC. Around the clock change this can be off by an hour.",
  "weekly.statusOpen": "open",
  "weekly.statusDone": "done",
  "weekly.statusStarted": "started",
  "weekly.lockoutAssumed": "lockout assumed",
  "weekly.allBossesKilled": "All bosses killed",
  "weekly.partiallyKilled": "Partially killed",
  "weekly.days": "{days}d",
  "weekly.shortened": " · shortened",
  "weekly.noCharacters": "No characters",
  "weekly.noCharactersHint": "The account has no characters for this game mode.",
  "weekly.characterFailed": "Not available",
  "weekly.noRaids": "No raids",
  "weekly.openOfTotal": "{open} of {total} open",
  "weekly.lastKnown": "Last known state",
  "weekly.lastKnownFrom": "Last known state from {date}",
  "weekly.failedText":
    "The raid endpoint did not answer for this character, and no earlier state is on file.",
  "weekly.noRaidData":
    "No raid data — the API returns nothing for characters that have never entered a raid.",
  "weekly.colInstance": "Instance",
  "weekly.colCleared": "Cleared this period",
  "weekly.colStatus": "Status",
  "weekly.colResetIn": "Reset in",
  "character.levelClass": "Level {level}",

  // ─── Charakterliste ──────────────────────────────────────────────────────
  "grid.apiError": "API error",
  "grid.statCharacters": "Characters",
  "grid.factionSplit": "{horde} Horde · {alliance} Alliance",
  "grid.statAvgItemLevel": "Ø item level",
  "grid.avgNote": "from {loaded} of {total} · highest {max}",
  "grid.avgPending": "loaded while scrolling",
  "grid.statHighestLevel": "Highest level",
  "grid.atMaxLevel": "{count} at max level",
  "grid.statFavorites": "Favourites",
  "grid.favoritesNote": "marked with ★",
  "grid.statRealms": "Realms",
  "grid.realmsNote": "spread across",
  "grid.filterAll": "All",
  "grid.favorites": "Favourites",
  "grid.searchPlaceholder": "Search character…",
  "grid.shownOf": "{shown} of {total} characters",
  "grid.realmCount": "{count} realms",
  "grid.colClass": "Cl.",
  "grid.colCharacter": "Character",
  "grid.noFavorites": "No favourites yet — click the ★ on a character.",
  "grid.noCharacters": "No characters found.",
  "grid.characterOne": "character",
  "grid.characterMany": "characters",
  "grid.loadingValues": "Loading values…",

  // ─── Einrichtung, Stufe 1 ────────────────────────────────────────────────
} as const

export const de: Record<keyof typeof en, string> = {

  "app.title": "WoW Dashboard",
  "app.description": "World-of-Warcraft-Account-Übersicht",
  "app.brand": "WOW DASHBOARD",
  "app.tagline": "Kaderliste / lokal",

  "header.apiConnected": "Dev-API verbunden",
  "header.firstFetch": "Erster Abruf läuft…",
  "header.updated": "Aktualisiert vor {seconds} Sek.",
  "header.pollEvery": "Abruf alle {seconds} Sek.",
  "header.charactersFound": "{count} Charaktere erkannt",
  "header.collections": "Sammlungen",
  "header.settings": "Einstellungen",
  "header.signOut": "Abmelden",

  "theme.label": "Farbschema",
  "theme.light": "Hell",
  "theme.dark": "Dunkel",

  "language.label": "Sprache",

  "dashboard.myCharacters": "Meine Charaktere",
  "dashboard.myCharactersHint":
    "Alle Charaktere des Accounts · Dev-API zieht automatisch nach",
  "dashboard.loading": "Lade…",
  "time.now": "jetzt",
  "time.daysHours": "{days} T {hours} Std.",
  "time.hoursMinutes": "{hours} Std. {minutes} Min.",
  "time.minutes": "{minutes} Min.",

  "mode.retail": "Retail",
  "mode.retail.note": "The War Within · Stufe 80",
  "mode.classic": "Classic",
  "mode.classic.note": "Anniversary · Stufe 60",
  "mode.classicEra": "Classic Era",
  "mode.classicEra.note": "Hardcore · Stufe 60",

  "tab.equipment": "Ausrüstung",
  "tab.equipment.note": "Angelegte Gegenstände und Loot-Kandidaten",
  "tab.professions": "Berufe",
  "tab.professions.note": "Fertigkeitsstufen und Rezepte",
  "tab.progress": "Fortschritt",
  "tab.progress.note": "Raids, Dungeons, Mythisch+",
  "tab.collections": "Sammlungen",
  "tab.collections.note": "Titel und Spielzeug",
  "tab.achievements": "Erfolge",
  "tab.achievements.note": "Erfolge nach Kategorie",
  "tab.reputation": "Ansehen",
  "tab.reputation.note": "Ruf bei Fraktionen",
  "tab.pvp": "PvP",
  "tab.pvp.note": "Wertungen und Schlachtfelder",
  "tab.guild": "Gilde",
  "tab.guild.note": "Mitglieder, Erfolge, Ereignisse",
  "tab.economy": "Wirtschaft",
  "tab.economy.note": "Herstellkosten gegen Verkaufspreis",
  "tab.logs": "Logs",
  "tab.logs.note": "Warcraft Logs",
  "tab.history": "Verlauf",
  "tab.history.note": "Entwicklung über Zeit",

  "card.itemLevel": "GS",
  "card.level": "Stufe",
  "card.averageItemLevel": "Ø ilvl",
  "card.faction": "Fraktion",
  "card.alliance": "Allianz",
  "card.horde": "Horde",
  "card.favoriteAdd": "Zu Favoriten hinzufügen",
  "card.favoriteRemove": "Aus Favoriten entfernen",
  "card.gear": "Ausrüstung",
  "card.loading": "Wird geladen",

  "weekly.link": "Wochenübersicht",
  "weekly.account": "{mode} · Account",
  "weekly.heading": "Wochenübersicht",
  "weekly.intro":
    "Was im laufenden Lockout-Zeitraum schon gelegt ist, abgeleitet aus dem Zeitpunkt des letzten Bosskills. Die Profil-API aktualisiert erst beim Ausloggen – wer noch in der Instanz steht, fehlt hier also noch.",
  "weekly.back": "← Zurück zur Kaderliste",
  "weekly.weeklyResetIn": "Wochenreset in",
  "weekly.dailyResetIn": "Tagesreset in",
  "weekly.dailyResetInUncertain": "Tagesreset in (Zeit unbelegt)",
  "weekly.openInstances": "Offene Instanzen",
  "weekly.region": "Region {region}",
  "weekly.regionAssumed":
    "Für diese Region sind die Resetzeiten nicht belegt; angezeigt werden die europäischen Werte.",
  "weekly.regionKnown":
    "Resetzeiten aus gepflegter Tabelle, gerechnet in UTC. Um die Zeitumstellung herum kann das eine Stunde abweichen.",
  "weekly.statusOpen": "offen",
  "weekly.statusDone": "erledigt",
  "weekly.statusStarted": "angefangen",
  "weekly.lockoutAssumed": "Lockout angenommen",
  "weekly.allBossesKilled": "Alle Bosse gelegt",
  "weekly.partiallyKilled": "Teilweise gelegt",
  "weekly.days": "{days} T",
  "weekly.shortened": " · verkürzt",
  "weekly.noCharacters": "Keine Charaktere",
  "weekly.noCharactersHint":
    "Für diesen Spielmodus liefert der Account keine Charaktere.",
  "weekly.characterFailed": "Nicht abrufbar",
  "weekly.noRaids": "Keine Schlachtzüge",
  "weekly.openOfTotal": "{open} offen von {total}",
  "weekly.lastKnown": "Letzter bekannter Stand",
  "weekly.lastKnownFrom": "Letzter bekannter Stand vom {date}",
  "weekly.failedText":
    "Der Schlachtzug-Endpunkt hat für diesen Charakter nicht geantwortet, und es liegt kein früherer Stand vor.",
  "weekly.noRaidData":
    "Keine Schlachtzug-Daten – für Charaktere, die nie einen Raid betreten haben, liefert die API nichts.",
  "weekly.colInstance": "Instanz",
  "weekly.colCleared": "Diesen Zeitraum gelegt",
  "weekly.colStatus": "Status",
  "weekly.colResetIn": "Reset in",
  "character.levelClass": "Stufe {level}",
  "grid.apiError": "API-Fehler",
  "grid.statCharacters": "Charaktere",
  "grid.factionSplit": "{horde} Horde · {alliance} Allianz",
  "grid.statAvgItemLevel": "Ø Gegenstandsstufe",
  "grid.avgNote": "aus {loaded} von {total} · Höchste {max}",
  "grid.avgPending": "wird beim Scrollen geladen",
  "grid.statHighestLevel": "Höchste Stufe",
  "grid.atMaxLevel": "{count} auf Höchststufe",
  "grid.statFavorites": "Favoriten",
  "grid.favoritesNote": "mit ★ markiert",
  "grid.statRealms": "Realms",
  "grid.realmsNote": "verteilt auf",
  "grid.filterAll": "Alle",
  "grid.favorites": "Favoriten",
  "grid.searchPlaceholder": "Charakter suchen…",
  "grid.shownOf": "{shown} von {total} Charakteren",
  "grid.realmCount": "{count} Realms",
  "grid.colClass": "Kl.",
  "grid.colCharacter": "Charakter",
  "grid.noFavorites": "Noch keine Favoriten gesetzt — ★ bei einem Charakter klicken.",
  "grid.noCharacters": "Keine Charaktere gefunden.",
  "grid.characterOne": "Charakter",
  "grid.characterMany": "Charaktere",
  "grid.loadingValues": "Lade Werte…",
}
